version: '3'
services:

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    restart: unless-stopped
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - '9000:9000'
    environment:
      - SONRQUBE_JDBC_USERNAME=sonar
      - SONRQUBE_JDBC_PASSWORD=sonar
      - SONRQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
   

  db:
    image: postgres:12
    container_name:db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_db:/var/lib/postgresql/10
      - postgresql_data:/var/lib/postgresql/10/data

 volumes:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_bundled-plugins:
    sonarqube_db:
    postgresql_data:
  

