version: 2.1
#orbs:
  #docker: circleci/docker@1.7.0
jobs:
  working_directory: ~/circlecimvn
  build:
    docker:
    - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn clean package
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - attach_workspace:
          at: .
      - run: docker build -t pgreeshma/circlemvn:v1 .
  push:
    machine:
      image: circlemvn:v1 
    steps: 
      - attach_workspace:
          at: .  
      - docker/check:
          registry: pgreeshma
          docker-username: pgreeshma  
          docker-password: pgr55shma
      - docker/push:
          image: circlemvn
          tag: v1
          registry: pgreeshma
      - run: docker push pgreeshma/circlemvn:v1

  deploy:
    docker:
    - image : pgreeshma/circlemvn:v1
    steps:
      - checkout
      - run: ssh docker run -d -p 8080:8080 --name tomcat1 pgreeshma/circlemvn:v1
workflow:
  build_push_deploy:
  jobs:
    - build
    - push:
        requires:
          - build
    - deploy:
        requires:
          - push
      

