version: 2.1
jobs:
  build:
    working_directory: /cimvn
      - run: chmod +x /cimvn
    docker:
      - image: cimg/openjdk:11.0  
      steps:
      - checkout
      - run: mvn clean package
  test:
  docker:
      - image: cimg/openjdk:11.0  
      steps:
      - checkout
      - run: mvn test
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
      
