version: 2.1
#orbs:
  #docker: circleci/docker@1.7.0
jobs:
  working_directory: ~/circlecimvn
  package:
    docker:
    - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn clean package
          
  build:
    docker:
    - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: docker build -t pgreeshma/circlemvn:v1 .
  push:
    docker:
    - image: pgreeshma/circlemvn:v1
    steps:
      - checkout
      #- run: docker login -u pgreeshma -p pgr55shma
      - run: docker push pgreeshma/circlemvn:v1

  deploy:
    docker:
    - image : pgreeshma/circlemvn:v1
    steps:
      - checkout
      - run: ssh docker run -d -p 8080:8080 --name tomcat1 pgreeshma/circlemvn:v1
workflow:
  version: 2.1
  full_workflow:
  jobs:
    - build
    - push:
      requires:
        - build
    - deploy:
      requires:
        - push
      

