version: 2.1
orbs:
  docker: circleci/docker@1.7.0
jobs:
  #working_directory: ~/circlecimvn
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: docker-compose up -d
      - run: mvn clean package
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      #- run: sudo systemctl service docker enable
      - attach_workspace:
          at: .
      - run: docker build -t pgreeshma/circlemvn:v1 .
      #- run: docker login -u pgreeshma --password pgr55shma
      - run: echo  "$docker_pass" | docker login --username pgreeshma --password-stdin
      - run: docker push pgreeshma/circlemvn:v1
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: docker-compose up -d
      - run: mvn sonar:sonar
  
  deploy:
    docker:
      - image : pgreeshma/circlemvn:v1
        auth:
          username: pgreeshma
          password: $docker_pass 
    steps:
      - run: 
          echo ssh localhost@127.0.0.1 docker run -d -p 8080:8080 --name tomcat1 pgreeshma/circlemvn:v1
workflows:
  build_deploy:
    jobs:
      - test
      - build:
          context: 
            - docker_creds
          requires:
            - test
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
